name: sensai
description: A new Flutter project.
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  flutter_sheet_localization: ^3.0.0
  vertical_weight_slider: ^2.5.0
  custom_cupertino_picker: ^2.0.3
  flutter_calendar_carousel: ^2.4.1
  http: ^0.13.3
  get: ^4.6.5
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  internet_connection_checker: ^1.0.0+1
  get_storage: ^2.1.1
  lib: ^0.0.3
  postgres: ^3.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit/Kanit-Light.ttf
          weight: 300

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
